wheel_data:
  wheels_name:
    - "lf_wheel"
    - "rf_wheel"
    - "rr_wheel"
    - "lr_wheel"
  lf_wheel:
    pos_on_vehicle_x:  0.24858
    pos_on_vehicle_y:  0.17929
  rf_wheel:
    pos_on_vehicle_x:  0.24858
    pos_on_vehicle_y: -0.18071
  rr_wheel:
    pos_on_vehicle_x: -0.28642
    pos_on_vehicle_y: -0.18071
  lr_wheel:
    pos_on_vehicle_x: -0.28642
    pos_on_vehicle_y:  0.17929